version: "3"

services:
   db_node_${domain}:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: sysadminsapi
        MYSQL_PASSWORD: passwordngerixx22
     container_name: wp_db_${domain}

   wordpress:
     depends_on:
        - db_node_${domain}
     image: wordpress:latest
     expose:
        - 80
     restart: always
     environment:
        VIRTUAL_HOST: ${domain}
        LETSENCRYPT_HOST: ${domain}
        LETSENCRYPT_EMAIL: sysadmin@${domain}
        WORDPRESS_DB_HOST: db_node_${domain}:3306
        WORDPRESS_DB_USER: sysadminsapi
        WORDPRESS_DB_PASSWORD: passwordngerixx22
     container_name: wp_${domain}
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
